# Generated by Django 5.2.7 on 2025-10-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the team", max_length=20, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="staffmember",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="staff.team",
            ),
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code displayed in calendar (e.g., D, L, 1, 2)",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        help_text="Hex color code for display",
                        max_length=7,
                    ),
                ),
                ("default_start_time", models.TimeField(blank=True, null=True)),
                ("default_end_time", models.TimeField(blank=True, null=True)),
                (
                    "default_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order for display in lists"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_types",
                        to="staff.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Type",
                "verbose_name_plural": "Shift Types",
                "ordering": ["team", "sort_order", "name"],
                "unique_together": {("team", "code")},
            },
        ),
    ]
