# Generated by Django 5.2.7 on 2025-10-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_team_staffmember_team_shifttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "availability_code",
                    models.CharField(
                        choices=[
                            ("X", "Unavailable"),
                            ("?", "Maybe Available (Prefer Not)"),
                            ("A", "Available"),
                        ],
                        default="A",
                        help_text="X=Unavailable, ?=Maybe Available, A=Available",
                        max_length=1,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_availability",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Availability",
                "verbose_name_plural": "Daily Availabilities",
                "ordering": ["date", "staff_member"],
                "indexes": [
                    models.Index(fields=["date"], name="staff_daily_date_ade443_idx"),
                    models.Index(
                        fields=["staff_member", "date"],
                        name="staff_daily_staff_m_c3894f_idx",
                    ),
                ],
                "unique_together": {("staff_member", "date")},
            },
        ),
    ]
