# Generated by Django 5.2.7 on 2025-10-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_dailyavailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyavailability",
            name="availability_code",
            field=models.CharField(
                choices=[
                    ("-", "Not Set"),
                    ("X", "Unavailable"),
                    ("?", "Maybe Available (Prefer Not)"),
                    ("A", "Available"),
                ],
                default="-",
                help_text="-=Not Set, X=Unavailable, ?=Maybe Available, A=Available",
                max_length=1,
            ),
        ),
    ]
