# Generated by Django 5.2.7 on 2025-10-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0001_initial"),
        ("staff", "0002_team_staffmember_team_shifttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="shift_type",
            field=models.ForeignKey(
                help_text="Type of shift (e.g., Day Shift Lead, Late Shift, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="staff.shifttype",
            ),
        ),
    ]
